### ISSUE TITLE
Syntax coloring for builtins

### ISSUE THREAD

**Issue by anton-trunov** [as1ndu/vscode-scilla#1]
As of today, the plugin only highlights `builtin` keyword, and considers the following name an ordinary identifier. However, those identifiers live in a different namespace so to speak. It would be great to have `to_uint32`, `concat`, etc. highlighted as well.

PS Thanks for you awesome work!

**Comment by as1ndu** [comment]
By built-in you mean arithmetic ( e.g `add`, `sub`),  Hashing (`ripemd160hash`, `keccak256hash`) etc?

**Comment by anton-trunov** [comment]
Yes, I do.

**Comment by anton-trunov** [comment]
Now I can see `eq` in `builtin eq` highlighted. However, `eq` gets highlighted even in contexts where it should not. Please consider the following piece of code:

```
let int_neq =
  tfun 'A =>
  fun (eq : 'A -> 'A -> Bool) =>
  fun (a : 'A) =>
  fun (b : 'A) =>
    let eqr = eq a b in.  (* eq get highlighted as a builtin, but it should not *)
    match eqr with
    | True => False
    | False => True
    end
```

**Comment by as1ndu** [comment]
So you are saying "eq" is only a valid  when used after the "builtin" keyword?

In ` fun (eq : 'A -> 'A -> Bool)`  isn't it an error to use key words like `eq` as variables/parameters in functions?

also so `(* eq get highlighted as a builtin, but it should not *)` was not highlighted (I have fixed that)

**Comment by anton-trunov** [comment]
Great questions, thank you!

> So you are saying "eq" is only a valid when used after the "builtin" keyword?

No, I am not saying that, quite the opposite. Builtins live in their own namespace. That's why you can't shadow them if you redefine `eq` (or any other builtin name).

> In fun (eq : 'A -> 'A -> Bool) isn't it an error to use key words like eq as variables/parameters in functions?

From the different namespaces design principle, it follows that it's not an error. However, to avoid confusion I'd recommend judicious reuse of builtin names for user names such as local `let`-bindings,  function parameters, etc.

**Comment by as1ndu** [comment]
So, far you only want keywords after the `builtin` keyword to be highlighted?

or is there something i am missing..

Also, should  `eq`  in ` fun (eq : 'A -> 'A -> Bool) =>` be highlighted as a built in?

**Comment by anton-trunov** [comment]
> Also, should eq in fun (eq : 'A -> 'A -> Bool) => be highlighted as a builtin?

No, it should not be highlighted as a builtin, because it's not a builtin.

**Comment by as1ndu** [comment]
Thanks will do a patch.
