### ISSUE TITLE
pairing scope terminators (`end`)

### ISSUE THREAD

**Issue by csajedi** [as1ndu/vscode-scilla#4]
I'd like to ask for insights into adding support for the scope-block features common in other languages. For now it seems scilla only concerns itself with `end` statements when considering scopes. This does not work for my in the vscode app as it its, and as my match statements and transitions grow it quickly becomes impossible to follow. 

In that regard, I am investigating how can I make it so that the plugin provides a common-sense indentation and `transition` / `match` - to - `end` pairing for scope? I will keep notes here in this thread and hope to submit a pull request if i get it working.

**Comment by as1ndu** [comment]
Yes, infact I am working on this right now in the Scilla format feature.

**Comment by as1ndu** [comment]
Hi, @csajedi 

I have finished implementing the code formatting feature and also added bracket support for transitions and matches. 

Please let me know if that solves your issue.
