### ISSUE TITLE
The name of this repository is somewhat confusing

### ISSUE THREAD

**Issue by anton-trunov** [as1ndu/vscode-scilla#5]
It's called `scilla`, but it would be better if you renamed it to reflect the nature of your project.
E.g. if someone decides to fork both the implementation of Scilla the language and this plugin, it might cause confusion.

I've seen people using `vscode-<language>` (e.g. `vscode-reasonml`) as the name of their VS Code language plugins and I would suggest to use something in that style, e.g. `vscode-scilla`.

**Comment by as1ndu** [comment]
True.

**Comment by anton-trunov** [comment]
Thanks a lot! The Scilla team is very excited about your work!
